// ./components/Dashboard/countryCodes.js
const countryData = {
'Afghanistan': { code: 'AF', color: '#8dd3c7', sizeFactor: 1.0 },
'Albania': { code: 'AL', color: '#ffffb3', sizeFactor: 0.8 },
'Algeria': { code: 'DZ', color: '#bebada', sizeFactor: 1.5 },
'Andorra': { code: 'AD', color: '#fb8072', sizeFactor: 0.5 },
'Angola': { code: 'AO', color: '#80b1d3', sizeFactor: 1.2 },
'Antigua and Barbuda': { code: 'AG', color: '#fdb462', sizeFactor: 0.5 },
'Argentina': { code: 'AR', color: '#b3de69', sizeFactor: 1.8 },
'Armenia': { code: 'AM', color: '#fccde5', sizeFactor: 0.8 },
'Australia': { code: 'AU', color: '#bc80bd', sizeFactor: 2.5 },
'Austria': { code: 'AT', color: '#ccebc5', sizeFactor: 0.7 },
'Azerbaijan': { code: 'AZ', color: '#ffed6f', sizeFactor: 0.9 },
'Bahamas': { code: 'BS', color: '#8dd3c7', sizeFactor: 0.6 },
'Bahrain': { code: 'BH', color: '#ffffb3', sizeFactor: 0.5 },
'Bangladesh': { code: 'BD', color: '#bebada', sizeFactor: 0.8 },
'Barbados': { code: 'BB', color: '#fb8072', sizeFactor: 0.5 },
'Belarus': { code: 'BY', color: '#80b1d3', sizeFactor: 1.0 },
'Belgium': { code: 'BE', color: '#fdb462', sizeFactor: 0.7 },
'Belize': { code: 'BZ', color: '#b3de69', sizeFactor: 0.6 },
'Benin': { code: 'BJ', color: '#fccde5', sizeFactor: 0.9 },
'Bhutan': { code: 'BT', color: '#bc80bd', sizeFactor: 0.8 },
'Bolivia': { code: 'BO', color: '#ccebc5', sizeFactor: 1.4 },
'Bosnia and Herzegovina': { code: 'BA', color: '#ffed6f', sizeFactor: 0.7 },
'Botswana': { code: 'BW', color: '#8dd3c7', sizeFactor: 1.3 },
'Brazil': { code: 'BR', color: '#ffffb3', sizeFactor: 2.2 },
'Brunei': { code: 'BN', color: '#bebada', sizeFactor: 0.5 },
'Bulgaria': { code: 'BG', color: '#fb8072', sizeFactor: 0.8 },
'Burkina Faso': { code: 'BF', color: '#80b1d3', sizeFactor: 1.0 },
'Burundi': { code: 'BI', color: '#fdb462', sizeFactor: 0.6 },
'Cabo Verde': { code: 'CV', color: '#b3de69', sizeFactor: 0.5 },
'Cambodia': { code: 'KH', color: '#fccde5', sizeFactor: 0.9 },
'Cameroon': { code: 'CM', color: '#bc80bd', sizeFactor: 1.1 },
'Canada': { code: 'CA', color: '#ccebc5', sizeFactor: 3.0 }, // Factor alto para país grande
'Central African Republic': { code: 'CF', color: '#ffed6f', sizeFactor: 1.2 },
'Chad': { code: 'TD', color: '#8dd3c7', sizeFactor: 1.4 },
'Chile': { code: 'CL', color: '#ffffb3', sizeFactor: 1.5 },
'China': { code: 'CN', color: '#bebada', sizeFactor: 2.8 }, // Factor alto para país grande
'Colombia': { code: 'CO', color: '#fb8072', sizeFactor: 1.3 },
'Comoros': { code: 'KM', color: '#80b1d3', sizeFactor: 0.5 },
'Congo (Congo-Brazzaville)': { code: 'CG', color: '#fdb462', sizeFactor: 1.0 },
'Costa Rica': { code: 'CR', color: '#b3de69', sizeFactor: 0.7 },
'Croatia': { code: 'HR', color: '#fccde5', sizeFactor: 0.7 },
'Cuba': { code: 'CU', color: '#bc80bd', sizeFactor: 0.9 },
'Cyprus': { code: 'CY', color: '#ccebc5', sizeFactor: 0.5 },
'Czechia (Czech Republic)': { code: 'CZ', color: '#ffed6f', sizeFactor: 0.7 },
'Democratic Republic of the Congo': { code: 'CD', color: '#8dd3c7', sizeFactor: 1.8 },
'Denmark': { code: 'DK', color: '#ffffb3', sizeFactor: 0.7 },
'Djibouti': { code: 'DJ', color: '#bebada', sizeFactor: 0.6 },
'Dominica': { code: 'DM', color: '#fb8072', sizeFactor: 0.5 },
'Dominican Republic': { code: 'DO', color: '#80b1d3', sizeFactor: 0.6 },
'Ecuador': { code: 'EC', color: '#fdb462', sizeFactor: 0.9 },
'Egypt': { code: 'EG', color: '#b3de69', sizeFactor: 1.2 },
'El Salvador': { code: 'SV', color: '#fccde5', sizeFactor: 0.6 },
'Equatorial Guinea': { code: 'GQ', color: '#bc80bd', sizeFactor: 0.6 },
'Eritrea': { code: 'ER', color: '#ccebc5', sizeFactor: 0.9 },
'Estonia': { code: 'EE', color: '#ffed6f', sizeFactor: 0.7 },
'Eswatini': { code: 'SZ', color: '#8dd3c7', sizeFactor: 0.5 },
'Ethiopia': { code: 'ET', color: '#ffffb3', sizeFactor: 1.3 },
'Fiji': { code: 'FJ', color: '#bebada', sizeFactor: 0.5 },
'Finland': { code: 'FI', color: '#fb8072', sizeFactor: 1.2 },
'France': { code: 'FR', color: '#80b1d3', sizeFactor: 1.0 },
'Gabon': { code: 'GA', color: '#fdb462', sizeFactor: 0.9 },
'Gambia': { code: 'GM', color: '#b3de69', sizeFactor: 0.5 },
'Georgia': { code: 'GE', color: '#fccde5', sizeFactor: 0.7 },
'Germany': { code: 'DE', color: '#bc80bd', sizeFactor: 0.8 },
'Ghana': { code: 'GH', color: '#ccebc5', sizeFactor: 0.8 },
'Greece': { code: 'GR', color: '#ffed6f', sizeFactor: 0.7 },
'Grenada': { code: 'GD', color: '#8dd3c7', sizeFactor: 0.5 },
'Guatemala': { code: 'GT', color: '#ffffb3', sizeFactor: 0.7 },
'Guinea': { code: 'GN', color: '#bebada', sizeFactor: 1.0 },
'Guinea-Bissau': { code: 'GW', color: '#fb8072', sizeFactor: 0.6 },
'Guyana': { code: 'GY', color: '#80b1d3', sizeFactor: 1.1 },
'Haiti': { code: 'HT', color: '#fdb462', sizeFactor: 0.6 },
'Honduras': { code: 'HN', color: '#b3de69', sizeFactor: 0.8 },
'Hungary': { code: 'HU', color: '#fccde5', sizeFactor: 0.7 },
'Iceland': { code: 'IS', color: '#bc80bd', sizeFactor: 0.9 },
'India': { code: 'IN', color: '#ccebc5', sizeFactor: 2.2 },
'Indonesia': { code: 'ID', color: '#ffed6f', sizeFactor: 1.5 },
'Iran': { code: 'IR', color: '#8dd3c7', sizeFactor: 1.5 },
'Iraq': { code: 'IQ', color: '#ffffb3', sizeFactor: 1.0 },
'Ireland': { code: 'IE', color: '#bebada', sizeFactor: 0.7 },
'Israel': { code: 'IL', color: '#fb8072', sizeFactor: 0.5 },
'Italy': { code: 'IT', color: '#80b1d3', sizeFactor: 0.8 },
'Ivory Coast': { code: 'CI', color: '#fdb462', sizeFactor: 0.9 },
'Jamaica': { code: 'JM', color: '#b3de69', sizeFactor: 0.5 },
'Japan': { code: 'JP', color: '#fccde5', sizeFactor: 1.0 },
'Jordan': { code: 'JO', color: '#bc80bd', sizeFactor: 0.7 },
'Kazakhstan': { code: 'KZ', color: '#ccebc5', sizeFactor: 2.5 },
'Kenya': { code: 'KE', color: '#ffed6f', sizeFactor: 1.0 },
'Kiribati': { code: 'KI', color: '#8dd3c7', sizeFactor: 0.5 },
'Korea, North': { code: 'KP', color: '#ffffb3', sizeFactor: 0.9 },
'Korea, South': { code: 'KR', color: '#bebada', sizeFactor: 0.7 },
'Kosovo': { code: 'XK', color: '#fb8072', sizeFactor: 0.5 },
'Kuwait': { code: 'KW', color: '#80b1d3', sizeFactor: 0.5 },
'Kyrgyzstan': { code: 'KG', color: '#fdb462', sizeFactor: 1.0 },
'Laos': { code: 'LA', color: '#b3de69', sizeFactor: 0.9 },
'Latvia': { code: 'LV', color: '#fccde5', sizeFactor: 0.7 },
'Lebanon': { code: 'LB', color: '#bc80bd', sizeFactor: 0.5 },
'Lesotho': { code: 'LS', color: '#ccebc5', sizeFactor: 0.5 },
'Liberia': { code: 'LR', color: '#ffed6f', sizeFactor: 0.7 },
'Libya': { code: 'LY', color: '#8dd3c7', sizeFactor: 1.5 },
'Liechtenstein': { code: 'LI', color: '#ffffb3', sizeFactor: 0.5 },
'Lithuania': { code: 'LT', color: '#bebada', sizeFactor: 0.7 },
'Luxembourg': { code: 'LU', color: '#fb8072', sizeFactor: 0.5 },
'Madagascar': { code: 'MG', color: '#80b1d3', sizeFactor: 1.4 },
'Malawi': { code: 'MW', color: '#fdb462', sizeFactor: 0.8 },
'Malaysia': { code: 'MY', color: '#b3de69', sizeFactor: 1.0 },
'Maldives': { code: 'MV', color: '#fccde5', sizeFactor: 0.5 },
'Mali': { code: 'ML', color: '#bc80bd', sizeFactor: 1.4 },
'Malta': { code: 'MT', color: '#ccebc5', sizeFactor: 0.5 },
'Marshall Islands': { code: 'MH', color: '#ffed6f', sizeFactor: 0.5 },
'Mauritania': { code: 'MR', color: '#8dd3c7', sizeFactor: 1.6 },
'Mauritius': { code: 'MU', color: '#ffffb3', sizeFactor: 0.5 },
'Mexico': { code: 'MX', color: '#bebada', sizeFactor: 1.5 },
'Micronesia': { code: 'FM', color: '#fb8072', sizeFactor: 0.5 },
'Moldova': { code: 'MD', color: '#80b1d3', sizeFactor: 0.6 },
'Monaco': { code: 'MC', color: '#fdb462', sizeFactor: 0.5 },
'Mongolia': { code: 'MN', color: '#b3de69', sizeFactor: 2.0 },
'Montenegro': { code: 'ME', color: '#fccde5', sizeFactor: 0.5 },
'Morocco': { code: 'MA', color: '#bc80bd', sizeFactor: 1.0 },
'Mozambique': { code: 'MZ', color: '#ccebc5', sizeFactor: 1.3 },
'Myanmar': { code: 'MM', color: '#ffed6f', sizeFactor: 1.2 },
'Namibia': { code: 'NA', color: '#8dd3c7', sizeFactor: 1.5 },
'Nauru': { code: 'NR', color: '#ffffb3', sizeFactor: 0.5 },
'Nepal': { code: 'NP', color: '#bebada', sizeFactor: 0.8 },
'Netherlands': { code: 'NL', color: '#fb8072', sizeFactor: 0.7 },
'New Zealand': { code: 'NZ', color: '#80b1d3', sizeFactor: 1.1 },
'Nicaragua': { code: 'NI', color: '#fdb462', sizeFactor: 0.8 },
'Niger': { code: 'NE', color: '#b3de69', sizeFactor: 1.6 },
'Nigeria': { code: 'NG', color: '#fccde5', sizeFactor: 1.0 },
'North Macedonia': { code: 'MK', color: '#bc80bd', sizeFactor: 0.5 },
'Norway': { code: 'NO', color: '#ccebc5', sizeFactor: 1.1 },
'Oman': { code: 'OM', color: '#ffed6f', sizeFactor: 1.1 },
'Pakistan': { code: 'PK', color: '#8dd3c7', sizeFactor: 1.4 },
'Palau': { code: 'PW', color: '#ffffb3', sizeFactor: 0.5 },
'Panama': { code: 'PA', color: '#bebada', sizeFactor: 0.8 },
'Papua New Guinea': { code: 'PG', color: '#fb8072', sizeFactor: 1.2 },
'Paraguay': { code: 'PY', color: '#80b1d3', sizeFactor: 1.0 },
'Peru': { code: 'PE', color: '#fdb462', sizeFactor: 1.4 },
'Philippines': { code: 'PH', color: '#b3de69', sizeFactor: 0.9 },
'Poland': { code: 'PL', color: '#fccde5', sizeFactor: 0.8 },
'Portugal': { code: 'PT', color: '#bc80bd', sizeFactor: 0.7 },
'Qatar': { code: 'QA', color: '#ccebc5', sizeFactor: 0.5 },
'Romania': { code: 'RO', color: '#ffed6f', sizeFactor: 0.9 },
'Russia': { code: 'RU', color: '#8dd3c7', sizeFactor: 3.5 }, // Factor muy alto
'Rwanda': { code: 'RW', color: '#ffffb3', sizeFactor: 0.6 },
'Saint Kitts and Nevis': { code: 'KN', color: '#bebada', sizeFactor: 0.5 },
'Saint Lucia': { code: 'LC', color: '#fb8072', sizeFactor: 0.5 },
'Saint Vincent and the Grenadines': { code: 'VC', color: '#80b1d3', sizeFactor: 0.5 },
'Samoa': { code: 'WS', color: '#fdb462', sizeFactor: 0.5 },
'San Marino': { code: 'SM', color: '#b3de69', sizeFactor: 0.5 },
'Sao Tome and Principe': { code: 'ST', color: '#fccde5', sizeFactor: 0.5 },
'Saudi Arabia': { code: 'SA', color: '#bc80bd', sizeFactor: 1.8 },
'Senegal': { code: 'SN', color: '#ccebc5', sizeFactor: 0.9 },
'Serbia': { code: 'RS', color: '#ffed6f', sizeFactor: 0.8 },
'Seychelles': { code: 'SC', color: '#8dd3c7', sizeFactor: 0.5 },
'Sierra Leone': { code: 'SL', color: '#ffffb3', sizeFactor: 0.7 },
'Singapore': { code: 'SG', color: '#bebada', sizeFactor: 0.5 },
'Slovakia': { code: 'SK', color: '#fb8072', sizeFactor: 0.7 },
'Slovenia': { code: 'SI', color: '#80b1d3', sizeFactor: 0.6 },
'Solomon Islands': { code: 'SB', color: '#fdb462', sizeFactor: 0.8 },
'Somalia': { code: 'SO', color: '#b3de69', sizeFactor: 1.5 },
'South Africa': { code: 'ZA', color: '#fccde5', sizeFactor: 1.6 },
'South Sudan': { code: 'SS', color: '#bc80bd', sizeFactor: 1.3 },
'Spain': { code: 'ES', color: '#ccebc5', sizeFactor: 1.1 },
'Sri Lanka': { code: 'LK', color: '#ffed6f', sizeFactor: 0.7 },
'Sudan': { code: 'SD', color: '#8dd3c7', sizeFactor: 1.8 },
'Suriname': { code: 'SR', color: '#ffffb3', sizeFactor: 1.0 },
'Sweden': { code: 'SE', color: '#bebada', sizeFactor: 1.4 },
'Switzerland': { code: 'CH', color: '#fb8072', sizeFactor: 0.6 },
'Syria': { code: 'SY', color: '#80b1d3', sizeFactor: 1.0 },
'Taiwan': { code: 'TW', color: '#fdb462', sizeFactor: 0.7 },
'Tajikistan': { code: 'TJ', color: '#b3de69', sizeFactor: 1.0 },
'Tanzania': { code: 'TZ', color: '#fccde5', sizeFactor: 1.4 },
'Thailand': { code: 'TH', color: '#bc80bd', sizeFactor: 1.1 },
'Timor-Leste': { code: 'TL', color: '#ccebc5', sizeFactor: 0.6 },
'Togo': { code: 'TG', color: '#ffed6f', sizeFactor: 0.6 },
'Tonga': { code: 'TO', color: '#8dd3c7', sizeFactor: 0.5 },
'Trinidad and Tobago': { code: 'TT', color: '#ffffb3', sizeFactor: 0.5 },
'Tunisia': { code: 'TN', color: '#bebada', sizeFactor: 0.9 },
'Turkey': { code: 'TR', color: '#fb8072', sizeFactor: 1.2 },
'Turkmenistan': { code: 'TM', color: '#80b1d3', sizeFactor: 1.5 },
'Tuvalu': { code: 'TV', color: '#fdb462', sizeFactor: 0.5 },
'Uganda': { code: 'UG', color: '#b3de69', sizeFactor: 0.8 },
'Ukraine': { code: 'UA', color: '#fccde5', sizeFactor: 1.3 },
'United Arab Emirates': { code: 'AE', color: '#bc80bd', sizeFactor: 0.7 },
'United Kingdom': { code: 'GB', color: '#ccebc5', sizeFactor: 0.8 },
'United States': { code: 'US', color: '#ffed6f', sizeFactor: 2.8 }, // Factor alto
'Uruguay': { code: 'UY', color: '#8dd3c7', sizeFactor: 0.9 },
'Uzbekistan': { code: 'UZ', color: '#ffffb3', sizeFactor: 1.3 },
'Vanuatu': { code: 'VU', color: '#bebada', sizeFactor: 0.5 },
'Vatican City': { code: 'VA', color: '#fb8072', sizeFactor: 0.5 },
'Venezuela': { code: 'VE', color: '#80b1d3', sizeFactor: 1.2 },
'Vietnam': { code: 'VN', color: '#fdb462', sizeFactor: 0.9 },
'Yemen': { code: 'YE', color: '#b3de69', sizeFactor: 1.2 },
'Zambia': { code: 'ZM', color: '#fccde5', sizeFactor: 1.3 },
'Zimbabwe': { code: 'ZW', color: '#bc80bd', sizeFactor: 1.0 }
};
// Objeto de conveniencia para mapear el nombre a la data (usado en StatsCharts.jsx)
export const countryNameToData = countryData;
// Objeto de conveniencia para mapear el nombre al código (usado en StatsCharts.jsx)
const countryNameToCode = Object.entries(countryData).reduce((acc, [name, data]) => {
acc[name] = data.code;
return acc;
}, {});
export default countryNameToCode;